### ISSUE TITLE
ovirt_vm_snapshot_min/max_age_minutes has a misleading label

### ISSUE THREAD

**Issue by crutonjohn** [czerwonk/ovirt_exporter#3]
While I was building Grafana dashboards using the prometheus metrics generated by this exporter, I came across an issue where I _thought_ that both `ovirt_vm_snapshot_min_age_minutes` and `ovirt_vm_snapshot_max_age_minutes` were measured in minutes as indicated by the naming scheme. After some poking around in the ovirt manager, I later realized that they were actually measured in seconds.

Typically prometheus metrics similar to these _are_ measured in seconds so there's no problems with that, so only the metric labels need to be updated.

I created a new pull request [here](https://github.com/czerwonk/ovirt_exporter/pull/2) that fixes the labels.

**Comment by czerwonk** [comment]
Fixed by #2
